export const defaultQuizzes = [
  {
    id: "1",
    title: "Science Basics",
    description: "Test your knowledge about basic science concepts",
    category: "Science",
    difficulty: "Easy",
    imageUrl: "/placeholder.jpg",
    createdBy: "QuizzieHub",
    defaultTimeLimit: 30,
    timesPlayed: Math.floor(Math.random() * 900) + 100,
    averageScore: Math.floor(Math.random() * 31) + 60,
    questions: [
      {
        id: "q1",
        text: "What is the chemical symbol for Gold?",
        options: ["Gd", "Au", "Go", "Gl"],
        correctAnswer: 1,
      },
      {
        id: "q2",
        text: "Which planet is known as the Red Planet?",
        options: ["Venus", "Mars", "Mercury", "Jupiter"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "2",
    title: "World Geography",
    description: "Challenge yourself with geography questions",
    category: "Geography",
    difficulty: "Medium",
    imageUrl: "/placeholder.jpg",
    createdBy: "QuizzieHub",
    defaultTimeLimit: 30,
    timesPlayed: Math.floor(Math.random() * 900) + 100,
    averageScore: Math.floor(Math.random() * 31) + 60,
    questions: [
      {
        id: "q1",
        text: "What is the capital of Australia?",
        options: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
        correctAnswer: 2,
      },
      {
        id: "q2",
        text: "Which is the largest ocean in the world?",
        options: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "3",
    title: "Sports Trivia",
    description: "Test your sports knowledge",
    category: "Sports",
    difficulty: "Medium",
    imageUrl: "/placeholder.jpg",
    createdBy: "QuizzieHub",
    defaultTimeLimit: 30,
    timesPlayed: Math.floor(Math.random() * 900) + 100,
    averageScore: Math.floor(Math.random() * 31) + 60,
    questions: [
      {
        id: "q1",
        text: 'In which sport is a "birdie" a term?',
        options: ["Tennis", "Cricket", "Golf", "Badminton"],
        correctAnswer: 2,
      },
      {
        id: "q2",
        text: "How many players are there in a basketball team on the court?",
        options: ["4", "5", "6", "7"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "4",
    title: "History Challenge",
    description: "Journey through important historical events",
    category: "History",
    difficulty: "Hard",
    imageUrl: "/placeholder.jpg",
    createdBy: "QuizzieHub",
    defaultTimeLimit: 30,
    timesPlayed: Math.floor(Math.random() * 900) + 100,
    averageScore: Math.floor(Math.random() * 31) + 60,
    questions: [
      {
        id: "q1",
        text: "In which year did the Titanic sink?",
        options: ["1910", "1912", "1915", "1920"],
        correctAnswer: 1,
      },
      {
        id: "q2",
        text: "Who was the first President of the United States?",
        options: ["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "5",
    title: "Movie Buffs",
    description: "How well do you know your movies?",
    category: "Movies",
    difficulty: "Medium",
    imageUrl: "/placeholder.jpg",
    createdBy: "QuizzieHub",
    defaultTimeLimit: 30,
    timesPlayed: Math.floor(Math.random() * 900) + 100,
    averageScore: Math.floor(Math.random() * 31) + 60,
    questions: [
      {
        id: "q1",
        text: "Who directed the movie 'Parasite'?",
        options: ["Quentin Tarantino", "Bong Joon-ho", "Christopher Nolan", "Martin Scorsese"],
        correctAnswer: 1,
      },
      {
        id: "q2",
        text: "What is the highest-grossing film of all time (unadjusted for inflation)?",
        options: ["Titanic", "Avatar", "Avengers: Endgame", "Star Wars: The Force Awakens"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "6",
    title: "Music Legends",
    description: "From rock to pop, test your music knowledge.",
    category: "Music",
    difficulty: "Easy",
    imageUrl: "/placeholder.jpg",
    createdBy: "QuizzieHub",
    defaultTimeLimit: 30,
    timesPlayed: Math.floor(Math.random() * 900) + 100,
    averageScore: Math.floor(Math.random() * 31) + 60,
    questions: [
      {
        id: "q1",
        text: "Who is known as the 'King of Pop'?",
        options: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"],
        correctAnswer: 1,
      },
      {
        id: "q2",
        text: "Which band released the album 'Abbey Road'?",
        options: ["The Rolling Stones", "The Who", "The Beatles", "Led Zeppelin"],
        correctAnswer: 2,
      },
    ],
  },
];
